flask_project/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask_project/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_project import db
from flask_project.models import Post
from flask_project.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='Новый пост', form=form, legend='Новый пост')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление поста', form=form, legend='Обновление поста')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))

flask_project/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_project import db, bcrypt
from flask_project.models import User, Post
from flask_project.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_project.users.utils import save_picture
from flask_project.users.utils import send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
        )

        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана!'
              ' Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, '
                  'проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        print('форма не валидна')
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

flask_project/templates/account.html
{% extends "layout.html" %}




{% block content %}
    <div class="container">
        <div class="px-5" style="margin-right: 20%; margin-left: 20%;">
              <div class="media">
                <img class="rounded-circle account-img" src="{{ image_file }}">
                <div class="media-body">
                  <h2 class="account-heading">{{ current_user.username }}</h2>
                  <p class="text-secondary">{{ current_user.email }}</p>
                </div>
              </div>

              <form method="POST" action="" enctype="multipart/form-data">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group">
                      <legend class="border-bottom mb-4">Аккаунт пользователя</legend>
                      <div class="form-group">
                          {{ form.username.label(class="form-control-label") }}

                          {% if form.username.errors %}
                              {{ form.username(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.username.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.username(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                      <div class="form-group">
                          {{ form.email.label(class="form-control-label") }}
                          {% if form.email.errors %}
                              {{ form.email(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.email.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.email(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                      <div class="form-group">
                          {{ form.picture.label() }}
                          {{ form.picture(class="form-control-file") }}
                          {% if form.picture.errors %}
                              {% for error in form.picture.errors %}
                                  <span class="text-danger">{{ error }}</span></br>
                              {% endfor %}
                          {% endif %}
                      </div>
                  </fieldset>
                  <div class="form-group">
                      {{ form.submit(class="btn btn-outline-info") }}
                  </div>
              </form>
        </div>
    </div>   



{% endblock content %}

flask_project/templates/allpost.html
{% extends "layout.html" %}



{% block content %}
  {% for post in posts.items %}
  <div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column;"> 
      <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" width="50">
      <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 0 auto;">{{ post.author.username }}</a>
    </article>

    <div class="card" style="margin-bottom: 20px;">
      <div class="card-body">
        <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <br>
        <br>
        <p class="card-text">{{ post.content }}</p>
      </div>
      <!-- <div class="card-footer" style="font-size: 20px;">
        <i class="fa fa-heart-o"></i>
        <i class="fa fa-bookmark-o"></i>
      </div> -->
    </div>
  </div>
  {% endfor %}

  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

flask_project/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
    <div class="px-5" style="margin-right: 20%; margin-left: 20%;" >
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group">
                        {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <br>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
    </div>
</div>
{% endblock content %}

flask_project/templates/home.html
{% extends "layout.html" %}

{% block content %}
<div class="container" style="margin: 12rem 4rem; text-align: center;">
    <div class="heading">
        <h1>ДОБРО ПОЖАЛОВАТЬ!📝</h1>
    </div>
    <hr class="w3-border-grey" style="margin:auto; width:40%;">
    <br>
    <div class="content-body">
        <p class="card-text" id="para">Добро пожаловать в мой <strong><em> блог!</em></strong>
            Большое спасибо за посещение. Я рад видеть вас на просторах моего блога! Это так здорово видеть
            вас здесь. Позвольте мне сказать вам одну вещь: вы можете не только просматривать
            новые посты, но и получать обновления...😄</p>
    </div>
    <br>

</div>
{% endblock content %}

flask_project/templates/layout.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for ('static', filename='main.css')}}">
    <link rel="stylesheet" href="{{ url_for ('static', filename='bootstrap.css')}}">

    {% if title %}
        <title>Flask-блог - {{ title }}</title>
    {% else %}
        <title>Flask-блог</title>
    {% endif %}


</head>
<body>
    <div class="header">
<!--            <img class="logo" src="{{ url_for('static', filename='img/logo.jpg')}}" alt="">-->
            <img class="logo" src="../static/img/logo.jpg" alt="">
            <div class="text">
                <ul class="menu">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('users.account') }}"><i class="fa fa-user"></i>Профиль</a></li>
                    <li><a href="{{url_for('posts.allpost') }}"><i class="fa fa-user"></i>Посты</a></li>
                    <li><a href="{{url_for('posts.new_post') }}"><i class="fa fa-user"></i>Создать Пост</a></li>
                    <li>Привет: {{ current_user.username }}</li>
                    {% endif %}
                </ul>
                <ul class="enter menu">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('users.logout') }}">Выйти</a></li>
                    {% else %}
                        <li><a href="{{url_for('users.login') }}">Войти</a></li>
                        <li><a href="{{url_for('users.register')}}">Зарегистрироваться</a></li>
                    {% endif %}
                </ul>
            </div>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <p class="coperite">© GB 2022 </p>
    </div>
</body>
</html>

flask_project/templates/login.html
{% extends "layout.html" %}


{% block content %}
<div class="container">
    <div class="py-5 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" fill="currentColor"
             class="bi bi-person-check-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
        </svg>
        <h2>Вход</h2>
    </div>
</div>

<div class="container">
    <div class="py-6">
        <form action="" method="post">
           {{ form.hidden_tag() }}
            <div class="col-sm-5 mx-auto">
                <div class="mb-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="mb-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="mb-3 form-check">
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>

                <button type="submit" class="btn btn-primary">Войти</button>
                <button type="submit" class="btn btn-light">
                    <a href="{{ url_for('users.register') }}">Зарегистрироваться</a>
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content%}

flask_project/templates/post.html
{% extends "layout.html" %}


{% block content %}
<div class="container" style="display: flex;">
  <article class="media" style="display: flex; flex-direction: column;"> 
    <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
  </article>
  
  <div class="card" style="margin-bottom: 20px;">
    <div class="card-body">
      <h4 class="card-title">{{ post.title }}</h4>
      <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
      <br>
      <br>
      <p class="card-text">{{ post.content }}</p>
    </div>
    <div class="card-footer" style="font-size: 20px;">
      <!-- <i class="fa fa-heart-o"></i>
      <i class="fa fa-bookmark-o"></i> -->
      {% if post.author == current_user %}
        <div class="card-footer" style="font-size: 20px; display: flex; justify-content: space-around">
          {% if post.author == current_user %}

            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id) }}">Обновить</a>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger btn-sm mt-1 mb-1" type="submit" value="Удалить">
            </form>
          {% endif %}
        </div>
      {% endif %}
    </div>
  </div>
</div>
  
<!-- Modal -->
<!--  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">-->
<!--    <div class="modal-dialog" role="document">-->
<!--      <div class="modal-content">-->
<!--        <div class="modal-header">-->
<!--          <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>-->
<!--          <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--            <span aria-hidden="true">&times;</span>-->
<!--          </button>-->
<!--        </div>-->
<!--        <div class="modal-footer">-->
<!--          <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>-->
<!--          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">-->
<!--            <input class="btn btn-danger" type="submit" value="Удалить">-->
<!--          </form>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
{% endblock content %}

flask_project/templates/register.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="py-5 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
        </svg>
        <h2>Регистрация</h2>
    </div>
</div>

<div class="container">
    <div class="py-6">
        <form action="" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="col-sm-5 mx-auto">
                <div class="mb-3">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="mb-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="mb-3">
                     {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="mb-3">
                   {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>



                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                <button type="submit" class="btn btn-light">
                    <a href="{{url_for('users.login') }}">
                        У меня уже есть аккаунт, войти</a>
                </button>

            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_project/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Сброс пароля</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Сброс пароля</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <div class="container">
      <article class="media">
        <img class="rounded-circle article-img"  src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      </article>

      <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
          <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

          <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
          <br>
          <br>
          <p class="card-text">{{ post.content }}</p>
        </div>
        <!-- <div class="card-footer" style="font-size: 20px;">
          <i class="fa fa-heart-o"></i>
          <i class="fa fa-bookmark-o"></i>
        </div> -->
      </div>
    </div>
    {% endfor %}


    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}